// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: inventory.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty.pb";

export const protobufPackage = "event";

export interface TicketClass {
  id: string;
  eventId: string;
  name: string;
  priceCents: number;
  currency: string;
  total: number;
  startSaleAt: string;
  endSaleAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTicketClassRequest {
  eventId: string;
  name: string;
  priceCents: number;
  currency: string;
  total: number;
  startSaleAt: string;
  endSaleAt: string;
}

export interface CreateTicketClassResponse {
  ticketClass: TicketClass | undefined;
}

export interface UpdateTicketClassRequest {
  id: string;
  name: string;
  priceCents: number;
  currency: string;
  total: number;
  startSaleAt: string;
  endSaleAt: string;
}

export interface UpdateTicketClassResponse {
  ticketClass: TicketClass | undefined;
}

export interface FindOneTicketClassRequest {
  id: string;
}

export interface FindOneTicketClassResponse {
  ticketClass: TicketClass | undefined;
}

export interface FindManyTicketClassRequest {
  eventId: string;
  ids: string[];
}

export interface FindManyTicketClassResponse {
  ticketClasses: TicketClass[];
}

export interface DeleteTicketClassRequest {
  id: string;
}

export interface ReserveItem {
  ticketClassId: string;
  quantity: number;
}

export interface ReserveRequest {
  orderCode: string;
  items: ReserveItem[];
  expiresAt: string;
}

export interface ConfirmRequest {
  orderCode: string;
}

export interface ReleaseRequest {
  orderCode: string;
}

export interface GetAvailabilityRequest {
  ticketClassId: string;
}

export interface GetAvailabilityResponse {
  availableQuantity: number;
}

export interface CheckAvailabilityItem {
  ticketClassId: string;
  quantity: number;
}

export interface CheckAvailabilityRequest {
  items: CheckAvailabilityItem[];
}

export interface CheckAvailabilityResponse {
  accept: boolean;
}

export const EVENT_PACKAGE_NAME = "event";

export interface InventoryServiceClient {
  createTicketClass(request: CreateTicketClassRequest): Observable<CreateTicketClassResponse>;

  updateTicketClass(request: UpdateTicketClassRequest): Observable<UpdateTicketClassResponse>;

  findOneTicketClass(request: FindOneTicketClassRequest): Observable<FindOneTicketClassResponse>;

  findManyTicketClass(request: FindManyTicketClassRequest): Observable<FindManyTicketClassResponse>;

  deleteTicketClass(request: DeleteTicketClassRequest): Observable<Empty>;

  checkAvailability(request: CheckAvailabilityRequest): Observable<CheckAvailabilityResponse>;

  getAvailability(request: GetAvailabilityRequest): Observable<GetAvailabilityResponse>;

  reserve(request: ReserveRequest): Observable<Empty>;

  confirm(request: ConfirmRequest): Observable<Empty>;

  release(request: ReleaseRequest): Observable<Empty>;
}

export interface InventoryServiceController {
  createTicketClass(
    request: CreateTicketClassRequest,
  ): Promise<CreateTicketClassResponse> | Observable<CreateTicketClassResponse> | CreateTicketClassResponse;

  updateTicketClass(
    request: UpdateTicketClassRequest,
  ): Promise<UpdateTicketClassResponse> | Observable<UpdateTicketClassResponse> | UpdateTicketClassResponse;

  findOneTicketClass(
    request: FindOneTicketClassRequest,
  ): Promise<FindOneTicketClassResponse> | Observable<FindOneTicketClassResponse> | FindOneTicketClassResponse;

  findManyTicketClass(
    request: FindManyTicketClassRequest,
  ): Promise<FindManyTicketClassResponse> | Observable<FindManyTicketClassResponse> | FindManyTicketClassResponse;

  deleteTicketClass(request: DeleteTicketClassRequest): void;

  checkAvailability(
    request: CheckAvailabilityRequest,
  ): Promise<CheckAvailabilityResponse> | Observable<CheckAvailabilityResponse> | CheckAvailabilityResponse;

  getAvailability(
    request: GetAvailabilityRequest,
  ): Promise<GetAvailabilityResponse> | Observable<GetAvailabilityResponse> | GetAvailabilityResponse;

  reserve(request: ReserveRequest): void;

  confirm(request: ConfirmRequest): void;

  release(request: ReleaseRequest): void;
}

export function InventoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTicketClass",
      "updateTicketClass",
      "findOneTicketClass",
      "findManyTicketClass",
      "deleteTicketClass",
      "checkAvailability",
      "getAvailability",
      "reserve",
      "confirm",
      "release",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InventoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InventoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INVENTORY_SERVICE_NAME = "InventoryService";
