// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty.pb";

export const protobufPackage = "user";

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  avatar: string;
  emailVerified: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateUserRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  avatar: string;
}

export interface CreateUserResponse {
  user: User | undefined;
}

export interface UpdateUserRequest {
  id: string;
  email: string;
  avatar: string;
  firstName: string;
  lastName: string;
  password: string;
}

export interface UpdateUserResponse {
  user: User | undefined;
}

export interface FindOneUserRequest {
  id?: string | undefined;
  email?: string | undefined;
}

export interface FindOneUserResponse {
  user: User | undefined;
}

export interface FindAllUserRequest {
  ids: string[];
  emails: string[];
}

export interface FindAllUserResponse {
  users: User[];
}

export interface DeleteUserRequest {
  id: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  create(request: CreateUserRequest): Observable<CreateUserResponse>;

  update(request: UpdateUserRequest): Observable<UpdateUserResponse>;

  findOne(request: FindOneUserRequest): Observable<FindOneUserResponse>;

  findAll(request: FindAllUserRequest): Observable<FindAllUserResponse>;

  delete(request: DeleteUserRequest): Observable<Empty>;
}

export interface UserServiceController {
  create(request: CreateUserRequest): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  update(request: UpdateUserRequest): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;

  findOne(
    request: FindOneUserRequest,
  ): Promise<FindOneUserResponse> | Observable<FindOneUserResponse> | FindOneUserResponse;

  findAll(
    request: FindAllUserRequest,
  ): Promise<FindAllUserResponse> | Observable<FindAllUserResponse> | FindAllUserResponse;

  delete(request: DeleteUserRequest): void;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "update", "findOne", "findAll", "delete"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
