// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: waitroom.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "waitroom.v1";

export enum SessionStatus {
  SESSION_STATUS_UNSPECIFIED = 0,
  SESSION_STATUS_QUEUED = 1,
  SESSION_STATUS_PROCESSING = 2,
  SESSION_STATUS_READY = 3,
  SESSION_STATUS_ACTIVE = 4,
  SESSION_STATUS_COMPLETED = 5,
  SESSION_STATUS_FAILED = 6,
  SESSION_STATUS_EXPIRED = 7,
  SESSION_STATUS_CANCELLED = 8,
  UNRECOGNIZED = -1,
}

export interface JoinQueueRequest {
  userId: string;
  eventId: string;
  userAgent: string;
  ipAddress: string;
}

export interface JoinQueueResponse {
  sessionId: string;
  position: number;
  queueLength: number;
  queuedAt: string;
  expiresAt: string;
  websocketUrl: string;
}

export interface GetQueueStatusRequest {
  sessionId: string;
}

export interface QueueStatusResponse {
  sessionId: string;
  status: SessionStatus;
  position: number;
  queueLength: number;
  queuedAt: string;
  expiresAt: string;
  checkoutToken: string;
  checkoutUrl: string;
  checkoutExpiresAt: string;
  admittedAt: string;
}

export interface LeaveQueueRequest {
  sessionId: string;
}

export interface LeaveQueueResponse {
  sessionId: string;
  message: string;
}

export interface StreamPositionRequest {
  sessionId: string;
}

export interface PositionUpdate {
  sessionId: string;
  position: number;
  queueLength: number;
  status: SessionStatus;
  updatedAt: string;
  checkoutToken: string;
  checkoutUrl: string;
}

export interface HealthCheckRequest {
}

export interface HealthCheckResponse {
  status: string;
  service: string;
  version: string;
  kafkaEnabled: boolean;
  components: { [key: string]: string };
}

export interface HealthCheckResponse_ComponentsEntry {
  key: string;
  value: string;
}

export const WAITROOM_V1_PACKAGE_NAME = "waitroom.v1";

export interface WaitroomServiceClient {
  joinQueue(request: JoinQueueRequest): Observable<JoinQueueResponse>;

  getQueueStatus(request: GetQueueStatusRequest): Observable<QueueStatusResponse>;

  leaveQueue(request: LeaveQueueRequest): Observable<LeaveQueueResponse>;

  streamQueuePosition(request: StreamPositionRequest): Observable<PositionUpdate>;

  healthCheck(request: HealthCheckRequest): Observable<HealthCheckResponse>;
}

export interface WaitroomServiceController {
  joinQueue(request: JoinQueueRequest): Promise<JoinQueueResponse> | Observable<JoinQueueResponse> | JoinQueueResponse;

  getQueueStatus(
    request: GetQueueStatusRequest,
  ): Promise<QueueStatusResponse> | Observable<QueueStatusResponse> | QueueStatusResponse;

  leaveQueue(
    request: LeaveQueueRequest,
  ): Promise<LeaveQueueResponse> | Observable<LeaveQueueResponse> | LeaveQueueResponse;

  streamQueuePosition(request: StreamPositionRequest): Observable<PositionUpdate>;

  healthCheck(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;
}

export function WaitroomServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["joinQueue", "getQueueStatus", "leaveQueue", "streamQueuePosition", "healthCheck"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WaitroomService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WaitroomService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WAITROOM_SERVICE_NAME = "WaitroomService";
